POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Lauluja",
  "author": "Helena",
  "url": "www.perunateatterit.fi",
  "likes": 9,
  "user": "5cde9eac4b57c834a0a7797c"
}