POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Lauluja",
  "author": "Helena",
  "url": "www.perunateatterit.fi",
  "likes": 9,
  "user": "5ce2a4a8177fff21d4e6045b"
}